function calculation = grincalculation(formulation,printer,...
                        n1,n2,discretization,grinprofile,shapeparameters,qty,spacings,offcenter,...
                        interlayerparameters,deltas,taus,gsvs,refresh,zinterval,savetopath)

m = discretization;
z = shapeparameters(end);

conversionRange = formulation.refractiveIndex.refractiveIndexModel.segments(2).conversionRange;
rifun = formulation.refractiveIndex.refractiveIndexModel.segments(2).fitting;
conversion = (conversionRange(1):0.001:conversionRange(2))';
refractiveindex = feval(rifun,conversion);

pixelsize = printer.pixelSize;

[baseimages,refractiveindices,~] = isoimages...
    (n1,n2,grinprofile,shapeparameters,discretization,pixelsize);

conversions = interp1(refractiveindex,conversion,refractiveindices);

conversioncells = mat2cell(conversions,ones(m,1));

[formulationcells{1:m,1}] = deal(formulation);
[printercells{1:m,1}] = deal(printer);
[targetthicknesscells{1:m,1}] = deal(z);
[deltacells{1:m,1}] = deal(deltas);
[taucells{1:m,1}] = deal(taus);
[gsvcells{1:m,1}] = deal(gsvs);
[refreshcells{1:m,1}] = deal(logical(refresh));
[zintervalcells{1:m,1}] = deal(zinterval);

predictions = cellfun(@calculateprintparams_uniformconversion,...
                formulationcells,printercells,targetthicknesscells,conversioncells,...
                deltacells,taucells,gsvcells,refreshcells,zintervalcells);

calculation = struct('formulation',formulation,'printer',printer,...
    'n1',n1,'n2',n2,'GRINprofile',grinprofile,'shapeParameters',shapeparameters,...
    'discretization',discretization,'conversions',conversions,...
    'refractiveIndices',refractiveindices,'baseImages',baseimages,...
    'predictions',predictions,'printConfiguration',[],...
    'refresh',logical(refresh),'zinterval',zinterval);


% calculation = struct('formulation',formulation,'printer',printer,...
%     'n1',n1,'n2',n2,'GRINprofile',grinprofile,'shapeParameters',shapeparameters,...
%     'discretization',discretization,'conversions',conversions,...
%     'refractiveIndices',refractiveindices,'baseImages',baseimages,...
%     'predictions',[],'printConfiguration',[],...
%     'refresh',logical(refresh),'zinterval',zinterval);

calculation =  recreatemonoimagesandbuildscript...
    (calculation, qty, spacings, offcenter, interlayerparameters, savetopath);